#!/bin/bash
cd /home/s296588/lab0
if [ -e $lab0 ]
then
	chmod -R 777 *
	cd ..
	rm -rf lab0
fi
if [ "$1" == "" ]; then
for var in ./script1 ./script2 ./script3 ./script4 ./script5
 	do 
		$var
	done
	exit
fi
if [ $1 -eq 1 ]; then
	for var in ./script1
	do 
		$var
	done
fi
if [ $1 -eq 2 ]; then
for var in ./script1 ./script2
	do 
		$var
	done
fi
if [ $1 -eq 3 ]; then
for var in ./script1 ./script2 ./script3
	do 
		$var
	done
fi
if [ $1 -eq 4 ]; then
for var in ./script1 ./script2 ./script3 ./script4
	do 
		$var
	done
fi
if [ $1 -eq 5 ]; then
for var in ./script1 ./script2 ./script3 ./script4 ./script5
 	do 
		$var
	done
fi